# Uncomment the next line to define a global platform for your project
# platform :ios, '9.0'

target 'CountApp' do
  # Comment the next line if you don't want to use dynamic frameworks
  use_frameworks!

  # Pods for CountApp
	pod 'RxSwift'
	pod 'RxCocoa'
	pod 'SnapKit'
	pod 'ReactorKit'

  target 'CountAppTests' do
    inherit! :search_paths
    # Pods for testing
  end

  target 'CountAppUITests' do
    # Pods for testing
  end

end
